# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...

apt-get update --fix-missing
apt-get install -q -y cowsay software-properties-common \
    make git curl tmux gcc build-essential

# Install nodejs
add-apt-repository -y ppa:chris-lea/node.js && apt-get update
apt-get install -q -y nodejs

# Install redis
apt-get install -y redis-server

echo "Ready to go!\n\nNode: $(node -v)" | /usr/games/cowsay

SCRIPT


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 4000, host: 4000
  config.vm.provision :shell, inline: $script
end
